name: agrotrilho_app
description: "Agrotrilho - Sistema de monitoramento de rebanho para pequenos produtores rurais."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobile_scanner: ^4.1.0
  qr_flutter: ^4.1.0
  nfc_manager: ^3.8.0+1
  uuid: ^4.0.0
  intl: ^0.19.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
